# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes_made', to='login.User')),
                ('pokie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes_recieved', to='login.User')),
            ],
        ),
    ]
